const constants = {
    ADD_MOVIE: 'ADD_MOVIE',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    TOGGLE_MODAL_WINDOW: 'TOGGLE_MODAL_WINDOW',
    CHANGE_SORTING_VALUE: 'CHANGE_SORTING_VALUE',
    CHANGE_FILTERING_VALUES: 'CHANGE_FILTERING_VALUES',
    GET_MOVIES: 'GET_MOVIES',
};

export default constants;